"""07

Revision ID: 229ba09f87cd
Revises: 76d55bc480fd
Create Date: 2023-10-29 14:54:22.704750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '229ba09f87cd'
down_revision = '76d55bc480fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chef', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.LargeBinary(),
               existing_nullable=True)

    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.LargeBinary(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('chef', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
