"""10

Revision ID: 2d85da90a736
Revises: 9c503331d0bd
Create Date: 2023-11-06 20:15:37.536423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d85da90a736'
down_revision = '9c503331d0bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chef', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', flask_appbuilder.models.mixins.ImageColumn(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chef', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
