"""04

Revision ID: 40d74879164b
Revises: 75d96132788b
Create Date: 2023-10-29 13:50:23.389092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40d74879164b'
down_revision = '75d96132788b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stars', sa.Enum('1', '2', '3', '4', '5', name='rating_enum'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.drop_column('stars')

    # ### end Alembic commands ###
