"""03

Revision ID: 75d96132788b
Revises: c2e68e687dde
Create Date: 2023-10-29 12:11:02.749879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75d96132788b'
down_revision = 'c2e68e687dde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chef_rating', schema=None) as batch_op:
        batch_op.alter_column('stars',
               existing_type=sa.INTEGER(),
               type_=sa.Enum('1', '2', '3', '4', '5', name='rating_enum'),
               existing_nullable=False)

    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.alter_column('stars',
               existing_type=sa.INTEGER(),
               type_=sa.Enum('1', '2', '3', '4', '5', name='rating_enum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.alter_column('stars',
               existing_type=sa.Enum('1', '2', '3', '4', '5', name='rating_enum'),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('chef_rating', schema=None) as batch_op:
        batch_op.alter_column('stars',
               existing_type=sa.Enum('1', '2', '3', '4', '5', name='rating_enum'),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
