"""08

Revision ID: 9a6bd216a228
Revises: 229ba09f87cd
Create Date: 2023-12-03 15:06:26.026252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a6bd216a228'
down_revision = '229ba09f87cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chef', schema=None) as batch_op:
        batch_op.drop_column('photo')

    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_column('average_rating')
        batch_op.drop_column('photo')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('rating_count')

    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.alter_column('food',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('svíčková', 'guláš', 'řízek', name='food_enum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.alter_column('food',
               existing_type=sa.Enum('svíčková', 'guláš', 'řízek', name='food_enum'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_count', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.BLOB(), nullable=True))
        batch_op.add_column(sa.Column('average_rating', sa.NUMERIC(), nullable=True))

    with op.batch_alter_table('chef', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.BLOB(), nullable=True))

    # ### end Alembic commands ###
