"""02

Revision ID: c2e68e687dde
Revises: 60edc5a016f1
Create Date: 2023-10-29 09:50:07.857025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2e68e687dde'
down_revision = '60edc5a016f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('opening_year', sa.Integer(), nullable=True),
    sa.Column('average_rating', sa.Numeric(), nullable=True),
    sa.Column('photo', sa.String(length=200), nullable=True),
    sa.Column('website', sa.String(length=100), nullable=True),
    sa.Column('ico', sa.String(length=15), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('opening_hours', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('registration_date', sa.Date(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chef',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('photo', sa.String(length=200), nullable=True),
    sa.Column('contact', sa.String(length=100), nullable=True),
    sa.Column('working_restaurant_id', sa.Integer(), nullable=True),
    sa.Column('average_rating', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['working_restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('food', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chef_rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('chef_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chef_id'], ['chef.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_name', sa.String(length=100), nullable=False),
    sa.Column('chef_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chef_id'], ['chef.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    op.drop_table('favorite_food')
    op.drop_table('chef_rating')
    op.drop_table('visit')
    op.drop_table('chef')
    op.drop_table('user')
    op.drop_table('restaurant')
    # ### end Alembic commands ###
