"""08

Revision ID: d1bf8649685b
Revises: 229ba09f87cd
Create Date: 2023-11-06 19:43:34.511388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1bf8649685b'
down_revision = '229ba09f87cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chef', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.LargeBinary(), nullable=True))
        batch_op.drop_column('photo')

    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_column('photo')

    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.alter_column('food',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('svíčková', 'guláš', 'řízek', name='food_enum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.alter_column('food',
               existing_type=sa.Enum('svíčková', 'guláš', 'řízek', name='food_enum'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.BLOB(), nullable=True))

    with op.batch_alter_table('chef', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.BLOB(), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###
